[general]
import = [
    "~/.config/alacritty/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.98
startup_mode = "Maximized"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 12
